$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: diabetes-pipeline-example

# <inputs_and_outputs>
inputs:
  pipeline_job_input: #using dataset, can use datastore + datapath also
    dataset: azureml:diabetes-data:1
    mode: download

outputs: 
  pipeline_job_cleaned_data:
    mode: upload
  pipeline_job_normalized_data:
    mode: upload
  pipeline_job_trained_model:
    mode: upload
# </inputs_and_outputs>

# <jobs>
compute: azureml:aml-cluster
settings:
  datastore: azureml:workspaceblobstore

jobs:
  stats-job:
    type: component
    component: file:./summary-stats.yml
    inputs:
      input_data: ${{inputs.pipeline_job_input}}

  fix-missing-job:
    type: component
    component: file:./fix-missing-data.yml
    inputs:
      input_data: ${{inputs.pipeline_job_input}}
    outputs:
      output_data: ${{outputs.pipeline_job_cleaned_data}}

  normalize-job:
    type: component
    component: file:./normalize.yml
    inputs:
      input_data: ${{jobs.fix-missing-job.outputs.output_data}}
    outputs:
      output_data: ${{outputs.pipeline_job_normalized_data}}

  train-job:
    type: component
    component: file:./train.yml
    inputs:
      training_data: ${{jobs.normalize-job.outputs.output_data}}
    outputs:
      model_output: ${{outputs.pipeline_job_trained_model}}
# </jobs>
