# <component>
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_decision_tree_classifier_model
display_name: Train a Decision Tree Classifier Model
version: 1
type: command
inputs:
  training_data: 
    type: uri_folder
outputs:
  model_output:
    type: uri_folder
code: ./src
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
command: >-
  python train-decision-tree.py 
  --training_data ${{inputs.training_data}} 
  --model_output ${{outputs.model_output}}
# </component>
