# <component>
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: TrainDecisionTreeClassifierModel
display_name: Train a Decision Tree Classifier Model
version: 1
type: command
inputs:
  training_data: 
    type: path
outputs:
  model_output:
    type: path
code:
  local_path: ./src
environment: azureml:basic-env-scikit:1
command: >-
  python train-decision-tree.py 
  --training_data ${{inputs.training_data}} 
  --model_output ${{outputs.model_output}}
# </component>
